// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57XjxiUBHgjoB5IiLFnPXR4DcmAfyOl0',
    appId: '1:393685952160:android:12fc71966dd3e673e40bc5',
    messagingSenderId: '393685952160',
    projectId: 'hidroponik-iot-29550',
    databaseURL: 'https://hidroponik-iot-29550-default-rtdb.firebaseio.com',
    storageBucket: 'hidroponik-iot-29550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu837VcAGK2dXegkJghqu6cMoC0QxDIvU',
    appId: '1:393685952160:ios:a200dbfb6a5a5cabe40bc5',
    messagingSenderId: '393685952160',
    projectId: 'hidroponik-iot-29550',
    databaseURL: 'https://hidroponik-iot-29550-default-rtdb.firebaseio.com',
    storageBucket: 'hidroponik-iot-29550.appspot.com',
    iosBundleId: 'com.example.hidroponikIot',
  );
}
